CREATE TABLE posts (pid SERIAL NOT NULL PRIMARY KEY, title VARCHAR (255) NOT NULL, description jsonb NOT NULL);
CREATE TABLE comments (cid SERIAL NOT NULL PRIMARY KEY, name VARCHAR (255) NOT NULL, description TEXT NOT NULL);
CREATE TABLE newsletter (neid SERIAL NOT NULL PRIMARY KEY, email VARCHAR (255) NOT NULL);
CREATE TABLE contact (ceid SERIAL NOT NULL PRIMARY KEY, name VARCHAR (255) NOT NULL, email VARCHAR (255) NOT NULL, description TEXT NOT NULL);